
package org.imt.nordeurope.j2ee.webservices.nickler.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TemperatureSoapWebService", targetNamespace = "http://nickler.webservices.j2ee.nordeurope.imt.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TemperatureSoapWebService {


    /**
     * 
     * @param country
     * @param value
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTemperature", targetNamespace = "http://nickler.webservices.j2ee.nordeurope.imt.org/", className = "org.imt.nordeurope.j2ee.webservices.nickler.client.GetTemperature")
    @ResponseWrapper(localName = "getTemperatureResponse", targetNamespace = "http://nickler.webservices.j2ee.nordeurope.imt.org/", className = "org.imt.nordeurope.j2ee.webservices.nickler.client.GetTemperatureResponse")
    @Action(input = "http://nickler.webservices.j2ee.nordeurope.imt.org/TemperatureSoapWebService/getTemperatureRequest", output = "http://nickler.webservices.j2ee.nordeurope.imt.org/TemperatureSoapWebService/getTemperatureResponse")
    public Integer getTemperature(
        @WebParam(name = "country", targetNamespace = "")
        String country,
        @WebParam(name = "value", targetNamespace = "")
        XMLGregorianCalendar value);

}
